export NIX_SKIP_KEYBASE_CHECKS=1

export _JAVA_AWT_WM_NONREPARENTING=1

export PATH="${HOME}/workareas.d/node_modules/bin:${PATH}"
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/.cargo/bin:${PATH}"
export NIX_PATH="${NIX_PATH:+$NIX_PATH:}unstable=$HOME/.nix-defexpr/channels/unstable"
